### ISSUE TITLE
UI stops rendering when dealing with nested objects.

### ISSUE THREAD

**Issue by matheus-rossi** [datacontract/datacontract-editor#2]
When working with nested objects, the UI stop rendering the contract visualization.

Consider the following contract:

```yml
dataContractSpecification: 0.9.3
id: urn:datacontract:checkout:orders-latest
info:
  title: Orders Latest
  version: 1.0.0

models:
  orders:
    description: One record per order. Includes cancelled and deleted orders.
    type: object
    fields:
      order_id:
        description: LoremIpsum
        required: true
        unique: true
        primary: true
      order_type:
        description: LoremIpsum
        type: object
        required: true
        fields:
          order_type:
            description: LoremIpsum
            required: true
            unique: true
            primary: true
```

When the nested object (order_type) is removed, the UI functions normally.
